name: 🚀 CI/CD

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        uses: ./
        with:
          packages: |
            helm=3.7.2*
            kustomize=4.4.1*
            kubectl=1.22.4*
